#!/bin/bash
# Download the certificate from the server

CURRENT=$(cd "$(dirname "$0")" && pwd)

AMAZON_ROOT_CA_URL="https://www.amazontrust.com/repository/AmazonRootCA1.pem"
RDS_CA_URL="https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem"

# Download the certificate for RDS Proxy.
cat <<EOF > "$CURRENT"/internal/certificate/rds_proxy.go
package certificate

// Code generated by download.sh; DO NOT EDIT.

// rdsProxyCertificate is the root certificate for RDS Proxy.
// It comes from $AMAZON_ROOT_CA_URL.
// See https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/rds-proxy.html#rds-proxy-connecting-iam for more details.
const rdsProxyCertificate = \`$(curl -sSL "$AMAZON_ROOT_CA_URL")\`
EOF

# Download the certificate for RDS MySQL.
cat <<EOF > "$CURRENT"/internal/certificate/rds.go
package certificate

// Code generated by download.sh; DO NOT EDIT.

// rdsCertificates the intermediate and root certificates for RDS MySQL.
// It comes from $RDS_CA_URL.
// See https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html#UsingWithRDS.SSL.CertificatesAllRegions for more details.
const rdsCertificates = \`$(curl -sSL "$RDS_CA_URL")\`
EOF

# for v2
curl -sSL "$AMAZON_ROOT_CA_URL" > "$CURRENT"/v2/internal/certificate/rds_proxy.pem
curl -sSL "$RDS_CA_URL" > "$CURRENT"/v2/internal/certificate/rds.pem
