# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines bellow are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  # rdsmysql
  - id: rdsmysql-amd64
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    main: ./cmd/rdsmysql
    binary: rdsmysql
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}
  - id: rdsmysql-arm64
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
    main: ./cmd/rdsmysql
    binary: rdsmysql
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}

  # rdsmysqldump
  - id: rdsmysqldump-amd64
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    main: ./cmd/rdsmysqldump
    binary: rdsmysqldump
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}
  - id: rdsmysqldump-arm64
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
    main: ./cmd/rdsmysqldump
    binary: rdsmysqldump
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}
archives:
  - formats: [tar.gz]
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
    ids:
      - rdsmysql-amd64
      - rdsmysql-arm64
      - rdsmysqldump-amd64
      - rdsmysqldump-arm64

changelog:
  use: github-native
  sort: asc

nfpms:
  # amd64 package
  - id: package-amd64
    builds:
      - rdsmysql-amd64
      - rdsmysqldump-amd64
    homepage: https://github.com/shogo82148/rdsmysql
    maintainer: ICHINOSE Shogo <shogo82148@gmail.com>
    description: MySQL Client Wrapper for IAM Database Authentication for Amazon RDS
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    release: 1
    epoch: 0
    bindir: /usr/bin

  # arm64 package
  - id: package-arm64
    builds:
      - rdsmysql-arm64
      - rdsmysqldump-arm64
    homepage: https://github.com/shogo82148/rdsmysql
    maintainer: ICHINOSE Shogo <shogo82148@gmail.com>
    description: MySQL Client Wrapper for IAM Database Authentication for Amazon RDS
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    release: 1
    epoch: 0
    bindir: /usr/bin

blobs:
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-amd64]
    directory: amazonlinux/2/x86_64/rdsmysql
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-arm64]
    directory: amazonlinux/2/aarch64/rdsmysql
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-amd64]
    directory: amazonlinux/2023/x86_64/rdsmysql
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-arm64]
    directory: amazonlinux/2023/aarch64/rdsmysql
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-amd64]
    directory: centos/7/x86_64/rdsmysql
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-arm64]
    directory: centos/7/aarch64/rdsmysql
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-amd64]
    directory: almalinux/8/x86_64/rdsmysql
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-arm64]
    directory: almalinux/8/aarch64/rdsmysql
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-amd64]
    directory: rockylinux/8/x86_64/rdsmysql
  - provider: s3
    bucket: shogo82148-rpm-temporary
    ids: [package-arm64]
    directory: rockylinux/8/aarch64/rdsmysql
